### ISSUE TITLE
Create / update site template button

### ISSUE THREAD

**Issue by kdanilkov** [truekonrads/casemanger#10]
![image](https://cloud.githubusercontent.com/assets/3965960/7782615/60c595a6-0129-11e5-85cd-c8cd2c8c6137.png)

I think that is not the correct place. Even I found it not in the Playground, but inside the incident web site.
The best place is beside Site actions for the site Administrators

**Comment by SarunasPikelis** [comment]
If possible, lets keep it in the page, since creating custom actions with dialogs takes time
