### ISSUE TITLE
Calculations of delay

### ISSUE THREAD

**Issue by kdanilkov** [truekonrads/casemanger#22]
Incidend: 
Expected Date (planned date or what ever to name)- the date we are getting from the Latest TASK planne end date.

SLA:
Value we copy from the IncidentType template to the incident instance. 
Can be changed by the authorized person.

In the dashboards we use:

StartDate + SLA and  Expected date relations

**Comment by SarunasPikelis** [comment]
What fields should contain calculated Value?
