### ISSUE TITLE
cannot assign task owner

### ISSUE THREAD

**Issue by truekonrads** [truekonrads/casemanger#55]
![image](https://cloud.githubusercontent.com/assets/1421150/8038767/5423f474-0dfd-11e5-80e2-83854c340d05.png)

**Comment by kdanilkov** [comment]
seems something wiith the sharepoint installation, as that is the default
functionality. It is only some time not working exacly in this environment
even where the EDF was not installed. working perfectly on the dev machine.

We will skip this in alpha testing, and retest in beta after the AZURE
reinstall


Best regards, Konstantin
